### ISSUE TITLE
Commenting not working

### ISSUE THREAD

**Issue by mysteryDate** [petereichinger/Unity3D-Shader#2]
The Ctrl+/ commenting is not working in either Sublime Text 2 or 3. The code here appears to account for comments:

 https://github.com/petereichinger/Unity3D-Shader/blob/master/UnityShader.tmLanguage#L22

  But I know nothing about creating Sublime Text packages... I DO know about Unity Shaders, however, and this repo is a lifesaver! Thanks a million.

**Comment by petereichinger** [comment]
I'll look into this tonight.

Thanks. Finally someone who finds this repo useful :laughing:

**Comment by mysteryDate** [comment]
Yeah! Super useful. I love ShaderLab, and I love Sublime Text. There are dozens of us! Dozens!

https://www.youtube.com/watch?v=lKie-vgUGdI

But honestly, MonoDevelop eats the bag... and don't even get me started on Visual Studio.

**Comment by petereichinger** [comment]
I hope this works. Is there anything else you want added?

**Comment by mysteryDate** [comment]
Works great! Thanks.

As for additions, there could be quite a few:
- Highlighting for a bunch of keywords: like #if, #define, uniform, POSITION, etc. Would there be a way to just import CG syntax highlighting between CGPROGRAM and ENDCG tags?
- Outside of CG, there are some built in Unity variables like UNITY_MATRIX_MVP that would be nice to highlight.
- Obviously auto-completion would be amazing, especially suggestions for vertex input and output structs. Like if you named the input to your fragment stage "i", then typing "i." would bring up a menu of variables in the struct, like i.vertex, i.uv, etc. 

If I had the time, I would try to handle these myself. Maybe some day? This is definitely not what I'm paid to do...
