### ISSUE TITLE
Function matches find subwords - e.g. ndoth has 'dot' highlighted

### ISSUE THREAD

**Issue by noisecrime** [petereichinger/Unity3D-Shader#6]
Hi,

Thanks for this package, very useful.

I noticed though that he current pattern matching for Functions will match subwords, for example if you created a variable to hold the result of 'n dot h' and call it ndoth then the 'dot' will be highlighted. Would be nice to avoid this. 

For now in my own fork of this I just copy & paste the regex for the Type match and applied it to Functions. Seems to work ok, but I know very little regex stuff so might not be the right way to go about it.

Oh one other change I made was to add cginc to the filetype since the main reason for using Sublime Text was that I wanted to be able to read and find stuff in Unity's cginc files easier. Again seems to work fine, but I suspect to do it properly would take more work and might be better as a new package.

**Comment by petereichinger** [comment]
Thanks for the comment :smile: 

I looked at the changes you made. Looks good :+1: .

By the way you only need to change the YAML file and compile it with Sublime.

As soon as I have time I will add your changes.

**Comment by petereichinger** [comment]
Sorry for the massive delay.

I implemented your changes and will publish an updated version really soon :)

Thank you!
