### ISSUE TITLE
Unable to Save Shader in new Buffer

### ISSUE THREAD

**Issue by robotron2084** [petereichinger/Unity3D-Shader#9]
I have repro-ed this bug on multiple machines, and have determined that uninstalling this package fixes the problem. Both machines are on OS X.

To Repro:
Copy this shader from pastebin:
https://pastebin.com/raw/dLAsfj0E
Open Sublime.
Go File-New to create a new buffer.
Paste the contents into the buffer.
Attempt to save the file.
Observer that the 'Save' button in the Save dialog is greyed out and cannot be enabled.

**Comment by petereichinger** [comment]
I fixed the problem :) thanks for reporting it

*edit* I'll publish a new version soon

**Comment by robotron2084** [comment]
Wow, man, you are awesome. I totally thought this was a dead repo, too! Thanks for doing that! 💃

**Comment by petereichinger** [comment]
Haha yeah, I'm not doing much with it. I'm not really sure what to do with it and I don't program that many shaders in Unity ATM unfortunately :/
